version: "3"

services:
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - $PWD/docker/postgres/data:/var/lib/postgresql/data:delegated
      - $PWD/docker/postgres/sql:/docker-entrhypoint-initdb.d:delegated
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=symfony
      - TZ=Asia/Tokyo

  web:
    build:
      context: ./docker/php-apache
      dockerfile: Dockerfile
    volumes:
      - $PWD/symfony:/var/www/html:delegated
      - $PWD/docker/php-apache/php.ini:/usr/local/etc/php/php.ini:delegated
    ports:
      - 8080:80
    depends_on:
      - db

  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  adminer:
    image: adminer:4.7-standalone
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: ng9
    ports:
      - "8081:8080"
    depends_on:
      - db
